### ISSUE TITLE
Missing detector data

### ISSUE THREAD

**Issue by dunnabhain1** [adus/portal-documentation#21]
When creating speed, flow, and density heatmaps for OR217 SB at MP 5.43 over a one-week time period, the resulting plots have a few hours with missing data. What might be a reason for this issue? Thanks!

**Comment by leetam** [comment]
@dunnabhain1 Can you provide the date range of the week you were looking at?

**Comment by dunnabhain1** [comment]
I pulled the 1-hr aggregated data sets for two date ranges: Mar. 17-25, 2019 and Mar. 22-30, 2020. The actual analyses covered the Mon. - Sun. periods of Mar. 18-24, 2019 and Mar. 23-29, respectively.

**Comment by leetam** [comment]
@dunnabhain1 we are looking into this issue and have flagged it for ODOT. An update will be provided once we hear back from them. Occasionally, there are glitches with the hardware/software, which might account for a missing hour here or there (doesn't occur often), but if it seems like there's a lot of missing data or it's happening frequently we'll look into it some more.

**Comment by dunnabhain1** [comment]
Great, thanks for the update and feedback!

**Comment by leetam** [comment]
@dunnabhain1 we done some internal checks and checked in with ODOT and nothing looks obviously suspicious or systemic. Sometimes we do experience system wide outages or some other type of internal processing issues, and when we do we will try to get a back-up of the missing data to fill in the gaps if it's available. However, with periodic data gaps we don't request back-up data to infill.
