### ISSUE TITLE
Misaligned Station Points on Map - Sunnyside/Sunnybrook and 205 NB

### ISSUE THREAD

**Issue by ben-chaney** [adus/portal-documentation#5]
Hi Folks, 

I believe the GIS locations for the station points for Sunnyside/Sunnybrook and 205 NB are misaligned.  Specifically, it looks like 2R054 and 2R053 are off.  It's not too much, but it's enough that an analyst asked me why we don't have those stations on PORTAL. 

I remember the topic of the station map locations coming up during a users meeting once, but I don't remember if it was something that's easy to change or hard to change. 

In any case, thanks!

~Ben

**Comment by leetam** [comment]
@ben-chaney we will look into this and get back to you.
