### ISSUE TITLE
Feedback link not found

### ISSUE THREAD

**Issue by ben-chaney** [adus/portal-documentation#6]
Hi Folks, 

The feedback link, in the incident data announcement banner at the bottom of station pages, leads to a "not found" page. 

http://new.portal.its.pdx.edu:8080/feedback/

![image](https://user-images.githubusercontent.com/10780100/54646987-1b7bf300-4a5e-11e9-9c3e-211c84763a35.png)

Thanks,
Ben

**Comment by leetam** [comment]
@ben-chaney thanks for flagging this for us, we'll get this fixed.

**Comment by basemelazzabi** [comment]
@leetam, The link is fixed to point to the current documentation/issues page where the viewer can find the "Post us an Issue" link.

These are the links to the PR [#207](https://github.com/adus/portal/pull/207) and [#208](https://github.com/adus/portal/pull/208).
