### ISSUE TITLE
Missing numberlanes data in station_metadata file

### ISSUE THREAD

**Issue by jbroach** [adus/portal-documentation#9]
Number of lanes shows up in the interactive station pages, but the _numberlanes_ field is empty in the station_metadata download file.

**Comment by kristinann** [comment]
Thanks @jbroach . I filed this as an issue in the main portal issue repository. @basemelazzabi is busy right now with a database migration and so is unable to do any coding at the moment, but we will get it on the list when he is back to coding.

If you'd like a data file with lane number information, we can get that for you, just let me know.
